global:
  slack_api_url: 'https://hooks.slack.com/services/T04M3CHC37E/B04M3CJD212/2W28SVh0WVtUwrqz7dcsWGX'

route:
  receiver: 'slack-notifications'
  repeat_interval: 2m
receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#_monitoring'
      send_resolved: true
      title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
      text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"