version: "3"
services:
  back:
    build:
      context: ./buyself-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./buyself-backend/:/buyself-backend/
    environment:
      FLASK_ENV: app

  react:
    build:
      context: ./frontend
    command: ["npm", "start"]
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/frontend
      - ./frontend/node_modules/:/frontend/node_modules